name: 'Build and autograde'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    name: 'Build Log'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assignment
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6
      - name: Build assignment and run tests
        run: mvn -V -ntp clean verify -Dmaven.test.failure.ignore=true | tee maven.log
      - name: Autograde assignment (tests and analysis)
        uses: uhafner/autograding-github-action@v1.7.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          CONFIG: >
            {
              "analysis": {
                "tools": [
                  {
                    "id": "error-prone",
                    "pattern": "**/*.log"
                  },
                  {
                    "id": "java",
                    "pattern": "**/*.log"
                  },
                  {
                    "id": "javadoc-warnings",
                    "pattern": "**/*.log"
                  },
                  {
                    "id": "checkstyle",
                    "pattern": "**/checkstyle-result.xml"
                  },
                  {
                    "id": "pmd",
                    "pattern": "**/pmd.xml"
                  },
                  {
                    "id": "spotbugs",
                    "pattern": "**/spotbugsXml.xml"
                  }
                ],
                "fileFilter": "Assignment[0-9][0-9].java",
                "typesIgnorePattern": "HideUtilityClassConstructorCheck|UseUtilityClass|UseVarargs",
                "maxScore": 20,
                "errorImpact": -5,
                "highImpact": -3,
                "normalImpact": -2,
                "lowImpact": -1
              },
              "tests": {
                "maxScore": 30,
                "failureImpact": -10,
                "skippedImpact": -10
              }
            }
